Frontend/design search results
ItsZil/neismesk pull request #42
Opened 2023-05-04 11:35 UTC by Rokki-R

2023-05-04 19:10 UTC, ItsZil commented
Dar tuo paciu jei nesunku padaryk kad kategorija turetu itakos search'ui, nes dabar neturi:

https://github.com/ItsZil/neismesk/blob/5a5eeff752b3bc32d896335b9bb2595f618b473e/Repositories/Item/ItemRepo.cs#L317

2023-05-07 12:38 UTC, ItsZil requested changes

2023-05-07 12:38 UTC, ItsZil commented on ClientApp/src/components/DetailedItemInfoPage/DetailedItemInfoPage.js
> +                setViewerId(2147483647);
Kas cia? neatrodo kaip geras sprendimas, gal galima kazkaip kitaip? ar cia testavimui buvo?

2023-05-07 12:38 UTC, ItsZil commented on ClientApp/src/components/NavMenu.js
>                              <Dropdown nav isOpen={this.state.dropdownOpen} toggle={this.toggleDropdown}>
Gal gali padaryti kad kategorijos nebutu hardcodintos, bet paimtos is duombazes? (tik gal pasiimk @JustasAn navbaro atnaujinimus kai sumergins)

2023-05-08 10:03 UTC, Rokki-R commented on ClientApp/src/components/DetailedItemInfoPage/DetailedItemInfoPage.js
> +                setViewerId(2147483647);
Pakeičiau

2023-05-08 10:03 UTC, Rokki-R commented on ClientApp/src/components/NavMenu.js
>                              <Dropdown nav isOpen={this.state.dropdownOpen} toggle={this.toggleDropdown}>
Done

2023-05-08 11:01 UTC, ItsZil approved these changes

2023-05-08 11:01 UTC, merged