Implemented repair shop creation
ItsZil/neismesk pull request #47
Opened 2023-05-11 16:38 UTC by Rokki-R

2023-05-12 09:59 UTC, ItsZil requested changes, later dismissed
perdaryt front'a iskart su react-boostrap gal geriau nei poto vel keist

2023-05-12 09:59 UTC, ItsZil commented on ClientApp/src/components/RepairShopCreationPage/RepairShopCreationPage.js
> +                <h2 className='itemBoxLabel'>Taisyklos reklamos sukūrimas</h2>
reklamos registracija gal (nes turesim patvirtint ir susisiekt ir pns)

2023-05-12 09:59 UTC, ItsZil commented on ClientApp/src/components/RepairShopCreationPage/RepairShopCreationPage.js
> +                            toast.success('Sėkmingai sukūrėtė reklamą!', {
gal reiktu ilgesnio ir aiskesnio pranesimo, pvz: 'Sėkmingai užregistravote reklamą, su Jumis susisieks administracija dėl sekančių žingsnių.' (jei cia ne per ilgas)

ir dar reiktu paciame frontende parasyti daugiau informacijos apie tai kaip ta reklama veikia (kad rodysime laimetojam derinant atsiemima, kaina individuali ir pateikiama mums susisiekus, nu cia sakinuka ar du)

2023-05-14 19:27 UTC, Ostinas approved these changes

2023-05-14 19:28 UTC, merged